package org.simple.clinic.bp.entry

enum class BloodPressureValidation {
  SUCCESS,
  ERROR_SYSTOLIC_EMPTY,
  ERROR_DIASTOLIC_EMPTY,
  ERROR_SYSTOLIC_TOO_HIGH,
  ERROR_SYSTOLIC_TOO_LOW,
  ERROR_DIASTOLIC_TOO_HIGH,
  ERROR_DIASTOLIC_TOO_LOW,
  ERROR_SYSTOLIC_LESS_THAN_DIASTOLIC
}
